### ISSUE TITLE
[Preparation] Δημιουργία backlog+roadmap για το παιχνίδι

### ISSUE THREAD

**Issue by vkyrillidis** [eap-pegasus-team/aranthia#11]
Στόχος του συγκεκριμένου task είναι η δημιουργία ενός απλοϊκού backlog για να μπορέσουμε να αποκτήσουμε σιγά σιγά σαν ομάδα περισσότερη "ταχύτητα" στο development.

Διεκπεραίωση:
- [x] Όλες οι εργασίες (tasks) είναι στη στήλη "Πρέπει να γίνουν"
- [x] Όλες οι εργασίες είναι λογικά χωρισμένες σε milestones (ορόσημα(;))
- [x] Δημιουργία διαγράμματος Gannt για σχετική εκτίμηση του χρόνου που χρειαζόμαστε
- [x] Περικοπή της έκτασης του έργου για να παραδώσουμε ένα MVP (ελάχιστο βιώσιμο προϊόν (;))

**Comment by vkyrillidis** [comment]
Setup Github για να σβήνει το branch αυτόματα.
