### ISSUE TITLE
[Epic] Stretch: Δημιουργία action RPG κομματιού του παιχνιδιού

### ISSUE THREAD

**Issue by vkyrillidis** [eap-pegasus-team/aranthia#26]
Δημιουργία action RPG κομματιού του παιχνιδιού όπου ο παίκτης καθώς περπατάει έξω από την ακαδημία, σε τυχαίο χρόνο του επιτίθενται εχθροί και έτσι πρέπει να τους πολεμήσει.

Στόχος είναι η δημιουργία των εξής:
- [ ] Δημιουργία χάρτη όπου ο παίκτης θα μπορεί να παίξει το action RPG κομμάτι του παιχνιδιού
- [ ] Δημιουργία μάχης (τύπου final fantasy)
- [ ] Γραφικά για τους εχθρούς
- [ ] Δημιουργία συστήματος διαχείρισης ζωής παίκτη
- [ ] Μετά από κάθε μάθημα, να ξεκλειδώνεται το αντίστοιχο ξόρκι
- [ ] Απλοϊκή ιστορία παράλληλα με τις μάχες

Σημείωση: Το συγκεκριμένο κομμάτι του παιχνιδιού θα το αφήσουμε για το τέλος και θα δουλέψουμε σε αυτό μόνο αν υπάρχει αρκετός χρόνος.
